steps:
- name: 'chaossystems/prototool:master'
  args: ['lint', '/workspace/src/proto']
  waitFor: -
- name: 'gcr.io/cloud-builders/gradle'
  args: ['build', 'gemFile']
  waitFor: -
- name: 'ruby:2.4'
  args: ['gem', 'build', 'protobuf-management.gemspec']
  dir: 'build/src/generated/main/ruby'
